#!/bin/bash

appid="325610"

# The working directory is Attila's game folder 
workshop_dir="${PWD}/../../workshop/content/${appid}"
gamedata_dir="${PWD}/data"
logfile_path="${PWD}/attila-forge.log"
scripts_dir="${HOME}/.Creative Assembly/Attila/scripts"
preferences_script_path="${scripts_dir}/preferences.script.txt"

game_path="./Attila"
appid_path="./steam_appid.txt"

packfile_prefix="mod."
default_save_name="modded_preferences.script.txt"

e_missing_arg=20
e_file_not_found=30

log_debug() {
  echo "$1" >> "${logfile_path}"
}

error_exit() {
  log_debug "Error: $2"
  exit $1
}

run_game() {
  log_debug "Execution completed. Running game..."
  exec "$game_path"
}

echo "Beggining execution." > "$logfile_path"

# Checking for `steam_appid.txt`
if [ ! -f "$appid_path" ] || ! grep -q "^$appid$" "$appid_path"; then
  log_debug "AppID file not found or invalid. Fixing issue."
  echo "$appid" > "$appid_path"
fi

# Load saved preferences script
if [ "$1" = "-l" -o "$1" = "--load" ]; then
  save_path=$default_save_name
  if [ $# -gt 1 ]; then
    save_path=$2
  fi
  save_path="$scripts_dir/$save_path"
  if [ ! -f "$save_path" ]; then
    error_exit 3 "preferences script not found at $save_path"
  fi
  cp -bf "$save_path" "$preferences_script_path"
  echo "Loaded preferences script."
  run_game
fi

# Remove existing mods from preferences script
sed -i 's/mod .*;//g' "$preferences_script_path"

# Save preferences script
if [ "$1" == "-o*" -o "$1" == "--output*" ]; then
  if grep -Eq "=.+$" <<< "$1"; then
    save_name=${1#*=}
  else
    save_name=$default_save_name
  fi
  shift
fi

# Copy .pack files and update preferences script
for arg in "$@"; do
  packfile_path=$(find "$workshop_dir" -maxdepth 2 \( -name "$arg" -o -name "${arg}.pack" \) -print -quit 2> /dev/null )
  if [ -z "$packfile_path" ]; then
    echo "Mod '$arg' not found. Skipping."
    continue
  fi
  packfile_basename=$(basename "$packfile_path")
  echo -n "$packfile_basename : Found"
  packfile_basename="${packfile_prefix}${packfile_basename}"
  if [ -f "${gamedata_dir}/${packfile_basename}" ]; then
    echo -n ", Already Copied"
  else
    cp "$packfile_path" "$gamedata_dir/${packfile_basename}"
    echo -n ", Copied"
  fi
  if grep -q "$packfile_basename" "$preferences_script_path"; then
    echo ", Already in Script"
  else
    echo "mod ${packfile_basename};" >> "$preferences_script_path"
    echo ", Script Updated"
  fi
done

# Save backup if option was set
if [ -n "$save_name" ]; then
  cp -i "$preferences_script_path" "${scripts_dir}/${save_name}"
  echo "Saved the preference script."
fi

run_game
